### ISSUE TITLE
Allow passing explicit derivative to Newton

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#45]

**Comment by Kolaru** [comment]
That would be a great feature to have (and to add to an already great package), and I would gladly implement it, but I am not sure how the possibility to pass the derivative should be reflected in the `roots` function.

The problem is that `roots` used with a `Bisection` contractor will not make use of the derivative, so it is tricky to keep a common interface. Some possibilities that I see are

- Define `roots(f, f_prime, contractor, X, tol)` and ignore the derivative and issue a warning if the contractor is `Bisection`. While it is probably the best possibility, it somehow feels wrong to be able to call a function with parameters that are sometime unused. Making it an error on the other hand may be an overkill.
- Define a specialized function to do that. Simple but we lose the neat unified interface.
- Allow to pass an instance of a contractor rather than a contractor type to `roots` . Add a method of the form `roots(contractor_instance, X, tol)` which may be confusing to users who do not know how the root finding algorithm work (actually the package make a very good job at hiding its internals).

**Comment by dpsanders** [comment]
Thanks for the suggestions. 

One thought I had was to allow to pass parameters like that to the `Newton` contractor itself, something like

```jl
roots(f, Newton(f_prime))
```
That was actually one of the motivations for having the contractors be separate objects.

**Comment by Kolaru** [comment]
I am fine with that version.

However I have a problem when testing my implementation, it looks like the test suite fail (using `Pkg.test("IntervalRootFinding")`) on both master branch and release v0.2.0. Is it a known issue or is something wrong with my setup ? I run Julia v0.6.2 on windows.

**Comment by Kolaru** [comment]
Actually don't bother with my problem, my installation is faulty.
